name: Build and Deploy to GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - src/**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: 安装依赖
        run: npm install -g corepack@latest && corepack enable pnpm && pnpm install

      - name: 构建
        run: pnpm run build

      - name: 提交
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: 部署
        id: deployment
        uses: actions/deploy-pages@v4
